### ISSUE TITLE
Incompatabilty with matplotlib 3.9 `register_cmap` no longer exists

### ISSUE THREAD

**Issue by ptiede** [liamedeiros/ehtplot#7]
Since matplotlib 3.3 `register_cmap` has been deprecated and the method no longer exists on matplotlib `3.9`. We should either add a compact bound or update the package to use the new API `matplotlib.colormaps.register`

**Comment by liamedeiros** [comment]
Fixed, thanks for flagging this Paul.

**Comment by empet** [comment]
👍
